### ISSUE TITLE
Shaders and ResourcePacks folders do not open with buttons

### ISSUE THREAD

**Issue by MindMusic** [flathub/com.lunarclient.LunarClient#20]
![image](https://github.com/flathub/com.lunarclient.LunarClient/assets/2808190/c73f60d4-d8f0-4b77-8b54-3a8902cb26af)

![image](https://github.com/flathub/com.lunarclient.LunarClient/assets/2808190/f2a1b8ca-b23d-4fae-9d6d-d941a220491d)

Clicking these buttons does nothing.  I don't even know where FlatPak stores these directories so I can't manually navigate.  Help please!

**Comment by Etaash-mathamsetty** [comment]
this is probably a minecraft bug actually, but I will debug this

**Comment by Etaash-mathamsetty** [comment]
yes it's a minecraft bug, closeable

**Comment by Etaash-mathamsetty** [comment]
yeah I don't get it
xdg-open within the sandbox works as well

**Comment by Doomsdayrs** [comment]
Flatpak stores data under `~/.var/`

**Comment by MindMusic** [comment]
> Flatpak stores data under `~/.var/`

Yeah, but where under ~/.var/?  Can't seem to find a folder anywhere called "shaderpacks" anywhere under there (or anywhere else for that matter)...  Exactly where is this folder supposed to be in the flatpak release?

**Comment by Doomsdayrs** [comment]
> > Flatpak stores data under `~/.var/`
> 
> Yeah, but where under ~/.var/? Can't seem to find a folder anywhere called "shaderpacks" anywhere under there (or anywhere else for that matter)... Exactly where is this folder supposed to be in the flatpak release?

The full path is
`~/.var/app/com.lunarclient.LunarClient/`

Inside you'll find three folders with relevant data
`.minecraft`, `.lunarclient`, `data`

I recall lunar client stores shaders and resource packs under `.minecraft`

**Comment by Doomsdayrs** [comment]
The following is an error log printed out when the mentioned button is pressed.

```
17:14:37.487 › [17:14:37] [Client thread/ERROR]: Couldn't open link
java.lang.reflect.InvocationTargetException: null
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at net.minecraft.client.gui.GuiScreenResourcePacks.actionPerformed(SourceFile:138) ~[?:?]
	at net.minecraft.client.gui.GuiScreen.redirect$zce000$impl$onMouseClicked(SourceFile:790) ~[?:?]
	at net.minecraft.client.gui.GuiScreen.mouseClicked(SourceFile:350) ~[?:?]
	at net.minecraft.client.gui.GuiScreenResourcePacks.mouseClicked(SourceFile:176) ~[?:?]
	at net.minecraft.client.gui.GuiScreen.handleMouseInput(SourceFile:413) ~[?:?]
	at net.minecraft.client.gui.GuiScreenResourcePacks.handleMouseInput(SourceFile:77) ~[?:?]
	at net.minecraft.client.gui.GuiScreen.handleInput(SourceFile:390) ~[?:?]
	at net.minecraft.client.Minecraft.runTick(SourceFile:1498) ~[?:?]
	at net.minecraft.client.Minecraft.runGameLoop(SourceFile:889) ~[?:?]
	at net.minecraft.client.Minecraft.run(SourceFile:325) ~[?:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at com.moonsworth.lunar.genesis.Genesis.main(Unknown Source) ~[?:?]
Caused by: java.lang.UnsupportedOperationException: The BROWSE action is not supported on the current platform!
	at java.awt.Desktop.checkActionSupport(Unknown Source) ~[?:?]
	at java.awt.Desktop.browse(Unknown Source) ~[?:?]
	... 20 more

17:14:37.488 › [17:14:37] [Client thread/INFO]: Opening via system class!

17:14:37.493 › java.io.IOException: Cannot run program "sensible-browser": error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(Unknown Source)

17:14:37.494 › 	at java.base/java.lang.ProcessBuilder.start(Unknown Source)
	at java.base/java.lang.Runtime.exec(Unknown Source)
	at java.base/java.lang.Runtime.exec(Unknown Source)
	at Genesis//org.lwjgl.LWJGLUtil$1.run(LWJGLUtil.java:406)
	at Genesis//org.lwjgl.LWJGLUtil$1.run(LWJGLUtil.java:404)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at Genesis//org.lwjgl.LWJGLUtil.execPrivileged(LWJGLUtil.java:404)
	at Genesis//org.lwjgl.LinuxSysImplementation.openURL(LinuxSysImplementation.java:78)
	at Genesis//org.lwjgl.Sys.openURL(Sys.java:257)
	at Genesis//net.minecraft.client.gui.GuiScreenResourcePacks.actionPerformed(SourceFile:145)
	at Genesis//net.minecraft.client.gui.GuiScreen.redirect$zce000$impl$onMouseClicked(SourceFile:790)
	at Genesis//net.minecraft.client.gui.GuiScreen.mouseClicked(SourceFile:350)
	at Genesis//net.minecraft.client.gui.GuiScreenResourcePacks.mouseClicked(SourceFile:176)
	at Genesis//net.minecraft.client.gui.GuiScreen.handleMouseInput(SourceFile:413)
	at Genesis//net.minecraft.client.gui.GuiScreenResourcePacks.handleMouseInput(SourceFile:77)
	at Genesis//net.minecraft.client.gui.GuiScreen.handleInput(SourceFile:390)
	at Genesis//net.minecraft.client.Minecraft.runTick(SourceFile:1498)
	at Genesis//net.minecraft.client.Minecraft.runGameLoop(SourceFile:889)
	at Genesis//net.minecraft.client.Minecraft.run(SourceFile:325)
	at Genesis//net.minecraft.client.main.Main.main(SourceFile:124)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at com.moonsworth.lunar.genesis.Genesis.main(Unknown Source)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(Unknown Source)
	at java.base/java.lang.ProcessImpl.start(Unknown Source)
	... 26 more
```
